# 时间同步工具
- name: Install chrony package
  become: yes
  package:
    name: chrony

- name: Setting NTP Server Config
  become: yes
  lineinfile:
    path: /etc/chrony.conf
    line: "{{ item }}"
    create: yes
  with_items: 
    - "{{ NtpServer }}"

- name: Chrony service enabled and start
  become: yes
  systemd:
      name: chronyd
      enabled: yes 
      state: restarted
